name: bible_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  dio: ^4.0.6
  url_strategy: ^0.2.0
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: K010
      fonts:
        - asset: assets/fonts/K010.ttf
